#!/bin/bash

set -e

USAGE="Usage: meta [original]"

if [ $# -lt 1 ]; then
  echo "$USAGE"
  exit 1
fi

ORIGINAL=$1

FILENAME=$(basename "$ORIGINAL")

[ "$WORKING_DIR" = "" ] && WORKING_DIR=.

META=$WORKING_DIR/meta__$FILENAME.txt

identify -verbose "$ORIGINAL" >>$META

echo "$META"

exit 0

