#!/bin/bash

set -e
set -x
usage()
{
  echo "process_file -b [bucket] -k [key] file" 
}

while getopts ":b:k:" opt; do
  case $opt in
    b)
      BUCKET=$OPTARG
      ;;
    k)
      KEY=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ -z "$BUCKET" ]; then
  usage
  exit 1
fi

shift $((OPTIND-1))

FILE=$1

if [ -z "$FILE" ]; then
  usage
  exit 1
fi

FILENAME=$(basename "$FILE")

if [ -z "$KEY" ]; then
  KEY=$FILENAME
fi

./s3put -b "$BUCKET" -k "$KEY" "$FILE"

RESOURCE_TYPE=$(./resourcetype "$FILE")

case $RESOURCE_TYPE in
  "Image")
    THUMB_COMMAND=./thumb
    RESOURCE_META=$(./meta "$FILE")
    ;;
  "Video")
    THUMB_COMMAND=./thumbv
    RESOURCE_META=$(./metav "$FILE")
    ;;
  "Other")
    exit 0
    ;;
esac

./resourceput -d "$BUCKET" -t "$RESOURCE_TYPE" -m "$RESOURCE_META" "$KEY"

variants=( 200x200 722x722 )

for DIMENSIONS in "${variants[@]}"
do
  COMMAND=("$THUMB_COMMAND" "-d" "$DIMENSIONS" "-n" "$FILE")

  THUMB=$(${COMMAND[@]})

  ./s3put -b "$BUCKET" -k "__thumbs/$DIMENSIONS/${KEY}.jpg" -c "image/jpeg" "$THUMB"
done

exit 0
