#!/bin/bash

set -e

usage()
{
  echo "process_dir -b [bucket] -p [prefix] dir" 
}

while getopts ":b:p:" opt; do
  case $opt in
    b)
      BUCKET=$OPTARG
      ;;
    p)
      PREFIX=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ -z "$BUCKET" ]; then
  usage
  exit 1
fi

shift $((OPTIND-1))

DIR=$1

if [ -z "$DIR" ]; then
  usage
  exit 1
fi

find -P "$DIR" -type f -print0 | while IFS= read -r -d $'\0' FILE; do
  KEY=${FILE:${#DIR}}
  KEY=${KEY#/}

  if [ ! -z "$PREFIX" ]; then
    KEY=$PREFIX/$KEY
  fi

  ./process_file -b "$BUCKET" -k "$KEY" "$FILE"
done

exit 0

