#!/bin/bash

set -e

usage()
{
  echo "process_file -b [bucket] -k [key] file" 
}

while getopts ":b:k:" opt; do
  case $opt in
    b)
      BUCKET=$OPTARG
      ;;
    k)
      KEY=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ -z "$BUCKET" ]; then
  usage
  exit 1
fi

shift $((OPTIND-1))

FILE=$1

if [ -z "$FILE" ]; then
  usage
  exit 1
fi

FILENAME=$(basename "$FILE")

if [ -z "$KEY" ]; then
  KEY="$FILENAME"
fi

./s3put -b "$BUCKET" -k "$KEY" "$FILE"

RESOURCE_TYPE=$(./resourcetype "$FILE")

case "$RESOURCE_TYPE" in
  "Image")
    RESOURCE_META=$(./meta "$FILE")
    ;;
  "Video")
    RESOURCE_META=$(./metav "$FILE")
    ;;
  "Other")
    exit 0
    ;;
esac

./resourceput -d "$BUCKET" -t "$RESOURCE_TYPE" -m "$RESOURCE_META" "$KEY"

variants=( 200x200 722x722 )

for DIMENSIONS in "${variants[@]}"
do
  case "$RESOURCE_TYPE" in
    "Image")
      THUMB=$(./thumb -d "$DIMENSIONS" -n "$FILE")
      ;;
    "Video")
      THUMB=$(./thumbv -d "$DIMENSIONS" -n "$FILE")
      ;;
  esac

  ./s3put -b "$BUCKET" -k "__thumbs/$DIMENSIONS/${KEY}.jpg" -c "image/jpeg" "$THUMB"

  unlink "$THUMB"
done

exit 0
