#!/bin/bash

set -e

usage()
{
  echo "process_dir -b [bucket] -p [prefix] -r [resume_file] dir" 
}

while getopts ":b:p:r:" opt; do
  case $opt in
    b)
      BUCKET=$OPTARG
      ;;
    p)
      PREFIX=$OPTARG
      ;;
    r)
      RESUME_FILE=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ -z "$BUCKET" ]; then
  usage
  exit 1
fi

shift $((OPTIND-1))

DIR=$1

if [ -z "$DIR" ]; then
  usage
  exit 1
fi

[ -z "$WORKING_DIR" ] && WORKING_DIR=.

find -P "$DIR" -type f -print0 | while IFS= read -r -d $'\0' FILE; do
  if [ "$RESUME_FILE" != "" ]; then
    if [ "$RESUME_FILE" != "$FILE" ]; then
      continue
    else
      RESUME_FILE=""
    fi
  fi

  KEY="${FILE:${#DIR}}"
  KEY="${KEY#/}"

  if [ ! -z "$PREFIX" ]; then
    KEY="$PREFIX/$KEY"
  fi

  ./process_file -b "$BUCKET" -k "$KEY" "$FILE"
done

exit 0

