#!/bin/bash

set -e

usage()
{
  echo "process_bucket -p [prefix] inbucket outbucket" 
}

while getopts ":p:" opt; do
  case $opt in
    p)
      PREFIX=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

[ "$WORKING_DIR" = "" ] && WORKING_DIR=.

shift $((OPTIND-1))

FROM_BUCKET=$1
TO_BUCKET=$2

if [ -z "$FROM_BUCKET" ] || [ -z "$TO_BUCKET" ]; then
  usage
  exit 1
fi

./s3list $FROM_BUCKET 100 | while IFS= read -r FROM_KEY; do
  FILE=$(./s3get -b "$FROM_BUCKET" "$FROM_KEY")

  TO_KEY="$FROM_KEY"
  [ ! -z "$PREFIX" ] && TO_KEY=$PREFIX/$TO_KEY

  ./process_file -b "$TO_BUCKET" -k "$TO_KEY" "$FILE"
done

exit 0

