#!/bin/bash

USAGE="Usage: s3filter [KEY] [TYPE]"

if [ $# -lt 1 ]; then
  echo "$USAGE"
  exit 1
fi

KEY=$1
TYPE=$2

RE_IMAGE="jpg$|png$|gif$|jpeg$|bmp$|crw$"
RE_VIDEO="mov$|mpeg$|mpg$|avi$|3gp$"

[ "$TYPE" = "" ] && TYPE="Image"

RE_MATCH=$RE_IMAGE
[ "$TYPE" = "Video" ] && RE_MATCH=$RE_VIDEO

BASENAME=$(basename "$KEY")
FILENAME="${BASENAME##*/}"
EXTENSION="${FILENAME##*.}"
EXTENSION_LOWER=$(echo "$EXTENSION" | tr '[:upper:]' '[:lower:]')

[[ $EXTENSION_LOWER =~ $RE_MATCH ]] && echo $KEY

exit 0

