#!/bin/bash

set -e

usage()
{
  echo "Usage: s3get -b [bucket] key1 key2 ..."
}

while getopts ":b:" opt; do
  case $opt in
    b)
      BUCKET=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ -z "$BUCKET" ]; then
  usage
  exit 1
fi

[ "$WORKING_DIR" = "" ] && WORKING_DIR=.

shift $((OPTIND-1))

for KEY in $@
do
  FILENAME=$(basename "$KEY")

  DESTINATION=$WORKING_DIR/$FILENAME

  aws s3api get-object --bucket "$BUCKET" --key "$KEY" "$DESTINATION" >>/dev/null

  echo "$DESTINATION"
done

exit 0

