#!/bin/bash

set -e

USAGE="Usage: s3list [BUCKET] [COUNT]"

if [ $# -lt 1 ]; then
  echo "$USAGE"
  exit 1
fi

BUCKET=$1
COUNT=$2

LIST_OBJECTS="aws s3api list-objects --output text --bucket $BUCKET --query Contents[].{Key:Key}"

[ "$COUNT" != "" ] && LIST_OBJECTS=" $LIST_OBJECTS --max-items $COUNT"

if [ "$COUNT" = "" ]; then
  $LIST_OBJECTS
else
  $LIST_OBJECTS | head -n $COUNT
fi

exit 0

