#!/bin/bash

set -e

usage()
{
  echo "Usage: s3put -b [bucket] -k [key] -c [content-type] file"
}

while getopts ":b:k:c:" opt; do
  case $opt in
    b)
      BUCKET=$OPTARG
      ;;
    k)
      KEY=$OPTARG
      ;;
    c)
      CONTENT_TYPE=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ -z "$BUCKET" ]; then
  usage
  exit 1
fi

shift $((OPTIND-1))

FILE=$1

if [ -z "$FILE" ]; then
  usage
  exit 1
fi

[ -z "$KEY" ] && KEY="${FILE##*/}"
[ -z "$CONTENT_TYPE" ] && CONTENT_TYPE="binary/octet-stream"

MD5SUM=$(openssl dgst -md5 -binary "$FILE" | openssl enc -base64)
 
aws s3api put-object --bucket "$BUCKET" --key "$KEY" --body "$FILE" --content-type $CONTENT_TYPE --content-md5 $MD5SUM >>/dev/null

echo "$BUCKET/$KEY"

shift
exit 0

