#!/bin/bash

set -e

usage()
{
  echo "Usage: s3put -b [bucket] -k [key] -c [content-type] -m [max-age] file"
}

while getopts ":b:k:c:m:" opt; do
  case $opt in
    b)
      BUCKET=$OPTARG
      ;;
    k)
      KEY=$OPTARG
      ;;
    c)
      CONTENT_TYPE=$OPTARG
      ;;
    m)
      MAX_AGE=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ -z "$BUCKET" ]; then
  usage
  exit 1
fi

shift $((OPTIND-1))

FILE=$1

if [ -z "$FILE" ]; then
  usage
  exit 1
fi

[ -z "$KEY" ] && KEY="${FILE##*/}"
[ -z "$CONTENT_TYPE" ] && CONTENT_TYPE=$(file --mime-type -b "$FILE")
[ -z "$MAX_AGE" ] && MAX_AGE=3600

MD5SUM=$(openssl dgst -md5 -binary "$FILE" | openssl enc -base64)
 
aws s3api put-object --bucket "$BUCKET" --key "$KEY" --body "$FILE" --content-type $CONTENT_TYPE --cache-control "max-age=${MAX_AGE}" --content-md5 $MD5SUM >>/dev/null

echo "$BUCKET/$KEY"

exit 0
