#!/bin/bash

set -e

usage()
{
  echo "Usage: thumb -n -d [dimensions] -q [quality] original1 original2 ..."
}

while getopts ":nd:q:" opt; do
  case $opt in
    n)
      NOPAD=1
      ;;
    d)
      DIMENSIONS=$OPTARG
      ;;
    q)
      QUALITY=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

[ -z "$WORKING_DIR" ] && WORKING_DIR=.
[ -z "$DIMENSIONS" ] && DIMENSIONS=200x200

mkdir -p "$WORKING_DIR/$DIMENSIONS"

[ -z "$QUALITY" ] && QUALITY=80

shift $((OPTIND-1))

while [ $# -gt 0 ]
do
  ORIGINAL=$1

  FILENAME=$(basename "$ORIGINAL")
 
  THUMB=$WORKING_DIR/$DIMENSIONS/$FILENAME.jpg

  if [ "$NOPAD" = "" ]; then
    convert "$ORIGINAL" -auto-orient +repage -thumbnail $DIMENSIONS -background white -gravity center -extent $DIMENSIONS -strip -interlace Plane -quality $QUALITY "$THUMB"
  else
    convert "$ORIGINAL" -auto-orient +repage -thumbnail $DIMENSIONS -strip -interlace Plane -quality $QUALITY "$THUMB"
  fi

  echo "$THUMB"

  shift
done

exit 0

